#!/bin/sh

./configure                  \
  --without-qt4              \
  --without-c_glib           \
  --without-csharp           \
  --without-java             \
  --without-erlang           \
  --without-nodejs           \
  --without-python           \
  --without-perl             \
  --without-php              \
  --without-php_extension    \
  --without-ruby             \
  --without-haskell          \
  --without-go               \
  --without-d
